version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - node
    networks:
      - desafio-fullcycle

  node:
    container_name: node
    restart: always
    build:
      context: ./node
    depends_on:
      - db
    networks:
      - desafio-fullcycle

  db:
    build:
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - desafio-fullcycle
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  desafio-fullcycle:
    driver: bridge
